



DATABASE_FILE_NAME:str = "data.db"
MAX_COIN_COUNT:int = 1024 #10bits
MAX_WALLET_COUNT:int = 256
PREMORTAL_WALLET_ADDRES=-1

NORMAL_TRANSACTION_FEE:int = 1
PREMORTAL_TRANSACTION_FEE:int = 0

NORMAL_TRANSACTION_DIFFICULTY:int = 3
PREMORTAL_TRANSACTION_DIFFICULTY:int = 3

PREMORTAL_MINING_REWARD:int = 2 #the only value that works

WALLET_KEY_LENGTH:int = 256
