



DATABASE_FILE_NAME:str = "data.db"
MAX_COIN_COUNT:int = 50 #10bits
MAX_WALLET_COUNT:int = 10
PREMORTAL_WALLET_ADDRES=-1
NORMAL_TRANSACTION_FEE:int = 1
PREMORTAL_TRANSACTION_FEE:int = 0
NORMAL_TRANSACTION_DIFFICULTY:int = 3
PREMORTAL_TRANSACTION_DIFFICULTY:int = 3
PREMORTAL_MINING_REWARD:int = 3 #the only value that works
WALLET_KEY_LENGTH:int = 1024
SIGNING_HASH_ALGHO_NAME:str = "SHA-256"
